// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsrDsy-JuvxigTs8m1Qp_wZEZn8ds_FX8',
    appId: '1:537385794315:ios:1dfb55fe38d9047bf8800e',
    messagingSenderId: '537385794315',
    projectId: 'hackathon-dashboard-98188',
    databaseURL: 'https://hackathon-dashboard-98188-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackathon-dashboard-98188.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2j34xv9ejpk3aGq1rn7LMLQmk_8tdgg',
    appId: '1:537385794315:web:ba45235b7643b3bcf8800e',
    messagingSenderId: '537385794315',
    projectId: 'hackathon-dashboard-98188',
    authDomain: 'hackathon-dashboard-98188.firebaseapp.com',
    databaseURL: 'https://hackathon-dashboard-98188-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackathon-dashboard-98188.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2j34xv9ejpk3aGq1rn7LMLQmk_8tdgg',
    appId: '1:537385794315:web:ba45235b7643b3bcf8800e',
    messagingSenderId: '537385794315',
    projectId: 'hackathon-dashboard-98188',
    authDomain: 'hackathon-dashboard-98188.firebaseapp.com',
    databaseURL: 'https://hackathon-dashboard-98188-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackathon-dashboard-98188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrDsy-JuvxigTs8m1Qp_wZEZn8ds_FX8',
    appId: '1:537385794315:ios:1dfb55fe38d9047bf8800e',
    messagingSenderId: '537385794315',
    projectId: 'hackathon-dashboard-98188',
    databaseURL: 'https://hackathon-dashboard-98188-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackathon-dashboard-98188.firebasestorage.app',
    iosBundleId: 'com.example.ecoTrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2orig7UrOzmZT1NLwZt2oKe2YYKOj9v0',
    appId: '1:537385794315:android:b80cfbcddb05663ff8800e',
    messagingSenderId: '537385794315',
    projectId: 'hackathon-dashboard-98188',
    databaseURL: 'https://hackathon-dashboard-98188-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hackathon-dashboard-98188.firebasestorage.app',
  );

}